package com.tw;

import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    static boolean exit = false;
    static ArrayList<Student> students = new ArrayList<>();
    public static void main(String args[]){
        while (!exit){
            printGuideInfo();
            String str = getInput();
            handleInput(str);
        }
    }
    private static void handleInput(String input) {
        switch (input){
            case "1":
                // 输入信息
            {
                System.out.println("请输入学生信息（格式：姓名, 学号, 学科: 成绩, ...），按回车提交：");
                String str = getInput();
                while (!formatCheck(str)){
                    System.out.println("请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：");
                    str = getInput();
                }
                students.add(getData(str));
                System.out.println("学生xxx的成绩被添加");
                break;
            }
            case "2":
            {
                // 打印成绩单
                System.out.println("请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：");
                String str = getInput();
                while (!formatCheck(str)){
                    System.out.println("请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：");
                    str = getInput();
                }
                ArrayList<String> ids = getIds(str);
                printScores(ids);
                break;
            }
            case "3":
                // 退出循环
                exit = true;
                System.out.println("exit...");
                break;
        }
    }

    private static ArrayList<String> getIds(String str) {
        ArrayList< String> ids = new ArrayList<>();
        ids.add("M201672189");
        return ids;
    }

    private static Student getData(String str) {
        Map<String,Integer> scores = new HashMap<>();
        scores.put("数学",149);
        scores.put("语文",149);
        scores.put("英语",149);
        scores.put("编程",149);
        scores.put("平均分",149);
        scores.put("总分",149);
        return new Student("骆小俊","M201672189",scores);
    }

    // 用来判断输入格式是否符合要求
    private static boolean formatCheck(String str) {
        // 姓名, 学号, 学科: 成绩, ...
        String regex = "[a-zA-Z0-9_],[a-zA-Z0-9_],(\\.[a-zA-Z0-9]+)+";
        return true;
    }

    private static void printScores(ArrayList<String> ids) {
        System.out.println("成绩单\n" + "姓名|数学|语文|英语|编程|平均分|总分");
        // 按照输入的学号的顺序打印成绩单
        for (String id : ids)
            for (Student student : students)
                if (id == student.getId()) {
                    System.out.println(student.getScores());
                    break;
                }
    }

    public static void printGuideInfo(){
        System.out.println(
                        "           1. 添加学生\n" +
                        "           2. 生成成绩单\n" +
                        "           3. 退出请输入你的选择（1～3）：");
    }
    public static String getInput(){
        Scanner input = new Scanner(System.in);
        return input.nextLine();
    }
    public boolean someLibraryMethod() {
        return true;
    }
}

class Student{
    private String name;
    private String id;
    private Map<String, Integer> scores;

    Student(String name, String id, Map<String,Integer>scores){
        this.name = name;
        this.id = id;
        this.scores = scores;
    }

    public String getId() {
        return id;
    }

    public String getScores() {
        // 姓名|数学|语文|英语|编程|平均分|总分
        return name + "|"+scores.get("数学")+ "|"+scores.get("语文")+ "|"+scores.get("英语")+ "|"+scores.get("编程")+ "|"+scores.get("平均分")+ "|"+scores.get("总分");
    }
}
