package com.tw;

import java.util.*;

import static java.lang.Integer.parseInt;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    static boolean exit = false;
    static ArrayList<Student> students = new ArrayList<>();
    public static void main(String args[]){
        while (!exit){
            printGuideInfo();
            String str = getInput();
            handleInput(str);
        }
    }
    private static void handleInput(String input) {
        switch (input){
            case "1":
                // 输入信息
            {
                System.out.println("请输入学生信息（格式：姓名, 学号, 学科: 成绩, ...），按回车提交：");
                String str = getInput();
                while (!formatCheck(str)){
                    System.out.println("请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：");
                    str = getInput();
                }
                Student stu = getData(str);
                students.add(stu);
                System.out.println("学生"+stu.getName()+"的成绩被添加");
                System.out.println(stu.getId());
                break;
            }
            case "2":
            {
                // 打印成绩单
                System.out.println("请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：");
                String str = getInput();
                ArrayList<String> ids = getIds(str);
                printScores(ids);
                break;
            }
            case "3":
                // 退出循环
                exit = true;
                System.out.println("exit...");
                break;
        }
    }

    private static ArrayList<String> getIds(String str) {
        ArrayList< String> ids = new ArrayList<>();
        String[] result = str.split(",");
        for (String id : result) {
            ids.add(id);
        }
        if (result.length == 0) ids.add(str);
        return ids;
    }

    private static Student getData(String str) {
        Map<String,Integer> scores = new HashMap<>();
        // 姓名, 学号, 学科: 成绩, ...4门课
        int sum = 0;
        String[] result = str.split(",");
        for (int i = 2; i < result.length; i++) {
            String[] score = result[i].split(":");
            int number = parseInt(score[1]);
            sum += number;
            scores.put(score[0],number);
        }
        scores.put("总分",sum);
        scores.put("平均分",sum/4);
        return new Student(result[0],result[1],scores);
    }

    // 用来判断输入格式是否符合要求
    public static boolean formatCheck(String str) {
        // 姓名, 学号, 学科: 成绩, ...4门课
        String[] result = str.split(",");
        if (result.length != 6) return false;
        for (int i = 2; i < result.length; i++) {
            String[] score = result[i].split(":");
            if (score.length != 2)
                return false;
            if (!score[1].matches("[0-9]+"))return false;
        }
        return true;
    }

    private static void printScores(ArrayList<String> ids) {
        System.out.println("成绩单\n" + "姓名|数学|语文|英语|编程|平均分|总分");
        // 按照输入的学号的顺序打印成绩单
        for (String id : ids){
            for (Student student : students){
                String studentId = student.getId();
                if (id.equals(studentId)) {
                    System.out.println(student.getScores());
                    break;
                }
            }
        }
    }

    public static void printGuideInfo(){
        System.out.println(
                        "           1. 添加学生\n" +
                        "           2. 生成成绩单\n" +
                        "           3. 退出请输入你的选择（1～3）：");
    }
    public static String getInput(){
        Scanner input = new Scanner(System.in);
        return input.nextLine();
    }
    public boolean someLibraryMethod() {
        return true;
    }
}

class Student{
    private String name;
    private String id;
    private Map<String, Integer> scores;

    Student(String name, String id, Map<String,Integer>scores){
        this.name = name;
        this.id = id;
        this.scores = scores;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getScores() {
        // 姓名|数学|语文|英语|编程|平均分|总分
        return name + "|"+scores.get("数学")+ "|"+scores.get("语文")+ "|"+scores.get("英语")+ "|"+scores.get("编程")+ "|"+scores.get("平均分")+ "|"+scores.get("总分");
    }
}
